# Generated by Django 5.2 on 2025-04-24 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='Numéro de facture')),
                ('invoice_symbol', models.CharField(max_length=20, verbose_name='Série de facture')),
                ('issued_date', models.DateField(verbose_name="Date d'émission")),
                ('payment_method', models.CharField(max_length=100, verbose_name='Méthode de paiement')),
                ('currency', models.CharField(default='VND', max_length=10, verbose_name='Devise')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Taux de change')),
                ('seller_name', models.CharField(max_length=255, verbose_name='Nom du vendeur')),
                ('seller_tax_code', models.CharField(max_length=20, verbose_name='Numéro fiscal du vendeur')),
                ('seller_address', models.TextField(verbose_name='Adresse du vendeur')),
                ('buyer_name', models.CharField(max_length=255, verbose_name="Nom de l'acheteur")),
                ('buyer_tax_code', models.CharField(max_length=20, verbose_name="Numéro fiscal de l'acheteur")),
                ('buyer_address', models.TextField(verbose_name="Adresse de l'acheteur")),
                ('total_before_tax', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total HT')),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant de la TVA')),
                ('total_after_tax', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total TTC')),
                ('total_in_words', models.TextField(verbose_name='Montant en lettres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(verbose_name='N° ligne')),
                ('name', models.CharField(max_length=255, verbose_name='Désignation')),
                ('unit', models.CharField(max_length=50, verbose_name='Unité')),
                ('quantity', models.FloatField(verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Prix unitaire')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant HT ligne')),
                ('vat_rate', models.CharField(max_length=10, verbose_name='Taux de TVA')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('vi', 'Tiếng Việt')], default='fr', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
