# Generated by Django 5.2 on 2025-04-24 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='import_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'importation"),
        ),
    ]
