# Generated by Django 5.2 on 2025-05-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_import_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='vat_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Taux de TVA'),
        ),
    ]
